[tool.poetry]
name = "btt-cli"
version = "0.1.0"
description = "Backup Tool for Telegram"
authors = ["oguzokdotdev <git@oguzok.tech>"]
readme = "README.md"
packages = [{include = "btt", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
hydrogram = "^0.2.0"
sqlalchemy = "^2.0.49"
aiosqlite = "^0.22.1"
typer = "^0.25.0"
platformdirs = "^4.9.6"
tgcrypto = "^1.2.5"

[tool.poetry.scripts]
btt = "btt.__main__:app"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"
pytest-asyncio = "^1.3.0"
sqlite-web = "^0.7.2"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
