[tool.poetry]
name = "btt-cli"
version = "0.1.0"
description = "Backup Tool for Telegram"
authors = ["oguzokdotdev <git@oguzok.tech>"]
readme = "README.md"
packages = [{include = "btt", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
hydrogram = "^0.2.0"
sqlalchemy = "^2.0.49"
aiosqlite = "^0.22.1"
typer = "^0.25.0"
platformdirs = "^4.9.6"

[tool.poetry.scripts]
btt = "btt.__main__:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
